

 import 'package:json_annotation/json_annotation.dart';

//الفايل ده هيبقى اوتو جنريتد واللي هيساعده ع كده البيلد رانر
 part 'users_model.g.dart';

 //استخدمت جيسون سيرياليزبل عشان اكتب كود اقل وتسهل عليا وبتعمل جينريت
  //الاات هى الانوتيشن الخاص بالليبرالي جيسون دي عشان اكتب كود اقل وتسهله عليا
 @JsonSerializable()

 // الموديل بعمله عشان يشيل الكي والفاليو بتاع الماب اللي بتظهر ف الايه بي ايي اللي هو البوست مان
  class UsersModel {

  // @JsonKey(name: 'idd')
   //دي اسمها انوتيشن بكتبها عشان اعرفهم ان موجود ف البوست مان كده الراجل غلط وكتبها اتنين دي
    int? id;
    String? name;
    String? email;
    String? gender;
    String? status;

    //وده الكونستراكتور الطبيعي اللسي هيخليني اكريت اوبجيكت من الكلاس
    UsersModel({this.id, this.name, this.email, this.gender, this.status});

    //وده الكونستراكتور اللي اسمه فروم جيسون اللي بياخد ماب اوف استرينج اللي هو الكي والديناميك اللي هو الفاليو وبيحولهم لاوبجيكت دارت عادي
    factory UsersModel.fromJson(Map<String, dynamic> json) => _$UsersModelFromJson(json);

    //و ده تو جيسون بيحولها تاني لجيسون والسهم اليساوي بيقولك الريتيرن وهو واللي فوقه هيتعملهم جينريت بسطر هيتكتب ف التيرمنال
    Map<String, dynamic> toJson() => _$UsersModelToJson(this);
 //معلومع حلوه ومهمه لو عايز تعمل سيرش عن كلمه او حاجه معينه ف باكيدج ع النت بدوس كنترول اف واكتب
//زي ماعملت ف الجيسون سيريابل عشان اعمل جنؤيت كتبت بيلد_رانر
//بنكتب ف التيرمنال dart run build_runner build

 }

 //كنت هكتبه كده وهكمل تاني بس الجيشسون سيرياليزابل ثبتت الجزء الاول وغيرت الباقي
 // class Autogenerated {
 //   int? id;
 //   String? name;
 //   String? email;
 //   String? gender;
 //   String? status;
 //
 //   Autogenerated({this.id, this.name, this.email, this.gender, this.status});
 //
 //   Autogenerated.fromJson(Map<String, dynamic> json) {
 //     id = json['id'];
 //     name = json['name'];
 //     email = json['email'];
 //     gender = json['gender'];
 //     status = json['status'];
 //   }
 //
 //   Map<String, dynamic> toJson() {
 //     final Map<String, dynamic> data = new Map<String, dynamic>();
 //     data['id'] = this.id;
 //     data['name'] = this.name;
 //     data['email'] = this.email;
 //     data['gender'] = this.gender;
 //     data['status'] = this.status;
 //     return data;
 //   }
 // }

